### ISSUE TITLE
render.blend file crashes upon start

### ISSUE THREAD

**Issue by markelwin** [mantyni/Multi-object-detection-lego#3]
The Blender application crashed with a segmentation fault or memory corruption upon loading of the render.blend file.

Blender 3.6.5
MacOS 14.1.1

Apologies for being unable to post a screenshot at this time.

**Comment by mantyni** [comment]
Thanks for sharing more information about the issue. I will test the code with Blender 3.6.5 and will get back soon with updates.

**Comment by mantyni** [comment]
@markelwin I've updated the repositoty with a Blender 3.65 compatible scene file and now it seems to work as expected. The issue I think was due to Blender 3.X not being backward compatible with Blender 2.X.

Just pull the updated repository and copy over the contents from `blender` folder into your Blender home dir. Then open the `Blender_3.65_Lego_rendering_scene.blend` file. Let me know if there are any further issues.

**Comment by markelwin** [comment]
Sorry here for radio silence. Thank you for the update. It works. 

I took the initiative to explore teaching myself the basics of Blender `bpy` this week so that I could construct a Blender environment for rendering LEGOs for realistic machine learning. I would love for you to help me continue to develop this.

I took this initiative to consolidate into one location a textbook of numerous introductory topics that introductory Blender Python and machine learning individuals want to know: rigid body physics, materials, mesh calculations, placement of multiple objects in an environments, rendering, and the beginning of resource management and processing. I found over and over again that searches for Blender `'bpy' refused to turn up single-source answers to these questions with consistent computer science paradigms, and so this new repository should drastically reduce the learning curve for machine learning individuals because these are common skills in machine learning. I hope the repository becomes the one-stop textbook for entry into Blender Python for the machine learning and LEGO communities, and I will be staffing the issues and reaching out to other community members as I develop out its utilities over the coming months and years. I would love for you to move your focus over to this new repository to help me build the project better, and to help any individuals that land on this page searching for Blender Python or machine learning to find the repository and reach out to me. There are vastly more individuals in this community than the resources currently seem to suggest, and I want to grow out these communities.

https://github.com/markelwin/LEGO.Emulation.Environment

Your work was invaluable for starting the project. Let's keep talking about all the items you are working on for yourself.

**Comment by mantyni** [comment]
Looks like a great initiative, nice work and good luck! I am a big fan of LEGO, it inspired me to pursue engineering career and it is really rewarding to see there is a growing software community around it.  

I will be maintaining my repository with new applied ML ideas when I have time (very limited these days), but if you have any questions or ideas feel free to reach out.

**Comment by markelwin** [comment]
Agreed. Feel free to share your contact information should you want to keep in touch. I noticed you have numerous AI/RL repositories and game engines. Both are extremely fascinating topics I also have a deep interest in. Reach out if you wish.
