### ISSUE TITLE
No images being generated

### ISSUE THREAD

**Issue by emilian** [mantyni/Multi-object-detection-lego#5]
Hi,

I installed Blender 3.6.5 for Mac OS (blender-3.6.5-macos-arm64.dmg). Installed all the required libraries (pip, pascal_voc_writer), and ran the provided script for the 3.6.5 version. The annotations are created, however, none of the images are saved. It's just an empty images folder.

Anybody else run into this issue?

**Comment by emilian** [comment]
It was an issue with the folder path. Make sure the images path is correct, and it should work.

**Comment by mantyni** [comment]
Hi @emilian , thanks for finding the solution and sorry for being slow to reply to issues. I am very busy these days. I'll update the repositiory instructions to double check images path. 

Thanks!
